from pydra.engine import specs
from pydra import ShellCommandTask
import typing as ty


def FLAMEO_output(inputs):
    import os, glob, attr

    def human_order_sorted(l):
        """
        Sorts string in human order (i.e. 'stat10' will go after 'stat2')
        """

        def atoi(text):
            return int(text) if text.isdigit() else text

        def natural_keys(text):
            if isinstance(text, tuple):
                text = text[0]
            return [atoi(c) for c in re.split(r"(\d+)", text)]

        return sorted(l, key=natural_keys)

    outputs = {}
    pth = os.path.join(os.getcwd(), inputs.log_dir)

    pes = human_order_sorted(glob(os.path.join(pth, "pe[0-9]*.*")))
    assert len(pes) >= 1, "No pe volumes generated by FSL Estimate"
    outputs["pes"] = pes

    res4d = human_order_sorted(glob(os.path.join(pth, "res4d.*")))
    assert len(res4d) == 1, "No residual volume generated by FSL Estimate"
    outputs["res4d"] = res4d[0]

    copes = human_order_sorted(glob(os.path.join(pth, "cope[0-9]*.*")))
    assert len(copes) >= 1, "No cope volumes generated by FSL CEstimate"
    outputs["copes"] = copes

    var_copes = human_order_sorted(glob(os.path.join(pth, "varcope[0-9]*.*")))
    assert len(var_copes) >= 1, "No varcope volumes generated by FSL CEstimate"
    outputs["var_copes"] = var_copes

    zstats = human_order_sorted(glob(os.path.join(pth, "zstat[0-9]*.*")))
    assert len(zstats) >= 1, "No zstat volumes generated by FSL CEstimate"
    outputs["zstats"] = zstats

    if inputs.f_con_file not in [None, attr.NOTHING]:
        zfstats = human_order_sorted(glob(os.path.join(pth, "zfstat[0-9]*.*")))
        assert len(zfstats) >= 1, "No zfstat volumes generated by FSL CEstimate"
        outputs["zfstats"] = zfstats

        fstats = human_order_sorted(glob(os.path.join(pth, "fstat[0-9]*.*")))
        assert len(fstats) >= 1, "No fstat volumes generated by FSL CEstimate"
        outputs["fstats"] = fstats

    tstats = human_order_sorted(glob(os.path.join(pth, "tstat[0-9]*.*")))
    assert len(tstats) >= 1, "No tstat volumes generated by FSL CEstimate"
    outputs["tstats"] = tstats

    mrefs = human_order_sorted(
        glob(os.path.join(pth, "mean_random_effects_var[0-9]*.*"))
    )
    assert len(mrefs) >= 1, "No mean random effects volumes generated by FLAMEO"
    outputs["mrefvars"] = mrefs

    tdof = human_order_sorted(glob(os.path.join(pth, "tdof_t[0-9]*.*")))
    assert len(tdof) >= 1, "No T dof volumes generated by FLAMEO"
    outputs["tdof"] = tdof

    weights = human_order_sorted(glob(os.path.join(pth, "weights[0-9]*.*")))
    assert len(weights) >= 1, "No weight volumes generated by FLAMEO"
    outputs["weights"] = weights

    outputs["stats_dir"] = pth

    return outputs


input_fields = [
    (
        "cope_file",
        specs.File,
        {
            "help_string": "cope regressor data file",
            "argstr": "--copefile={cope_file}",
            "mandatory": True,
        },
    ),
    (
        "var_cope_file",
        specs.File,
        {
            "help_string": "varcope weightings data file",
            "argstr": "--varcopefile={var_cope_file}",
        },
    ),
    (
        "dof_var_cope_file",
        specs.File,
        {
            "help_string": "dof data file for varcope data",
            "argstr": "--dofvarcopefile={dof_var_cope_file}",
        },
    ),
    (
        "mask_file",
        specs.File,
        {
            "help_string": "mask file",
            "argstr": "--maskfile={mask_file}",
            "mandatory": True,
        },
    ),
    (
        "design_file",
        specs.File,
        {
            "help_string": "design matrix file",
            "argstr": "--designfile={design_file}",
            "mandatory": True,
        },
    ),
    (
        "t_con_file",
        specs.File,
        {
            "help_string": "ascii matrix specifying t-contrasts",
            "argstr": "--tcontrastsfile={t_con_file}",
            "mandatory": True,
        },
    ),
    (
        "f_con_file",
        specs.File,
        {
            "help_string": "ascii matrix specifying f-contrasts",
            "argstr": "--fcontrastsfile={f_con_file}",
        },
    ),
    (
        "cov_split_file",
        specs.File,
        {
            "help_string": "ascii matrix specifying the groups the covariance is split into",
            "argstr": "--covsplitfile={cov_split_file}",
            "mandatory": True,
        },
    ),
    (
        "run_mode",
        ty.Any,
        {
            "help_string": "inference to perform",
            "argstr": "--runmode={run_mode}",
            "mandatory": True,
        },
    ),
    (
        "n_jumps",
        int,
        {"help_string": "number of jumps made by mcmc", "argstr": "--njumps={n_jumps}"},
    ),
    (
        "burnin",
        int,
        {
            "help_string": "number of jumps at start of mcmc to be discarded",
            "argstr": "--burnin={burnin}",
        },
    ),
    (
        "sample_every",
        int,
        {
            "help_string": "number of jumps for each sample",
            "argstr": "--sampleevery={sample_every}",
        },
    ),
    ("fix_mean", bool, {"help_string": "fix mean for tfit", "argstr": "--fixmean"}),
    (
        "infer_outliers",
        bool,
        {"help_string": "infer outliers - not for fe", "argstr": "--inferoutliers"},
    ),
    (
        "no_pe_outputs",
        bool,
        {"help_string": "do not output pe files", "argstr": "--nopeoutput"},
    ),
    (
        "sigma_dofs",
        int,
        {
            "help_string": "sigma (in mm) to use for Gaussian smoothing the DOFs in FLAME 2. Default is 1mm, -1 indicates no smoothing",
            "argstr": "--sigma_dofs={sigma_dofs}",
        },
    ),
    (
        "outlier_iter",
        int,
        {
            "help_string": "Number of max iterations to use when inferring outliers. Default is 12.",
            "argstr": "--ioni={outlier_iter}",
        },
    ),
    ("log_dir", ty.Any, "stats", {"help_string": "", "argstr": "--ld={log_dir}"}),
]
FLAMEO_input_spec = specs.SpecInfo(
    name="Input", fields=input_fields, bases=(specs.ShellSpec,)
)

output_fields = []
FLAMEO_output_spec = specs.SpecInfo(
    name="Output", fields=output_fields, bases=(specs.ShellOutSpec,)
)


class FLAMEO(ShellCommandTask):
    """
    Example
    -------
    >>> task = FLAMEO()
    >>> task.inputs.cope_file = "cope_merged.nii.gz"
    >>> task.inputs.var_cope_file = "varcope_merged.nii.gz"
    >>> task.inputs.cov_split_file = "design.grp"
    >>> task.inputs.design_file = "design.mat"
    >>> task.inputs.t_con_file = "design.con"
    >>> task.inputs.mask_file = "mask.nii.gz"
    >>> task.inputs.run_mode = "fe"
    >>> task.cmdline
    'flameo --copefile=cope_merged.nii.gz --covsplitfile=design.grp --designfile=design.mat --ld=stats --maskfile=mask.nii.gz --runmode=fe --tcontrastsfile=design.con --varcopefile=varcope_merged.nii.gz'
    """

    input_spec = FLAMEO_input_spec
    output_spec = FLAMEO_output_spec
    executable = "flameo"
